
/rat/db/set DETECTOR experiment "XLZD60"
/rat/db/set DETECTOR geo_file "XLZD60/XLZD.geo"
/rat/db/load XLZD60/ELEMENTS.ratdb
/rat/db/load XLZD60/MATERIALS_XLZD.ratdb
/rat/db/load XLZD60/OPTICS_XLZD.ratdb
/rat/db/load XLZD60/PMT.ratdb
/rat/db/load XLZD60/cryo.geo
/rat/db/load XLZD60/TPC.geo
/rat/db/load XLZD60/PTFE.ratdb
/rat/db/load XLZD60/PMTINFO_inner.ratdb


/run/initialize

#/vis/open RayTracer
#/vis/open VRML2FILE
/vis/open OGLSQt
#/vis/open DAWNFILE
/vis/scene/create
/vis/scene/add/volume
/vis/sceneHandler/attach

/vis/viewer/addCutawayPlane 0 0 0 cm 1 0 0

/vis/viewer/set/upVector 0.0 0.0 1.0
/vis/viewer/set/viewpointThetaPhi -95 -30
/vis/viewer/zoomTo 1.5
/vis/viewer/set/style s
#/vis/viewer/flush
/vis/viewer/refresh

# BEGIN EVENT LOOP
#/rat/proc simpledaq
#/rat/proc count
#/rat/procset update 10

#/rat/proclast outroot
#/rat/procset file "basic_test.root"
#END EVENT LOOP

#/generator/add combo gun2:point
#/generator/vtx/set neutron  1 0 0 0 10.0 10.0
#/generator/pos/set -3500 0 0

#/run/beamOn 10
